### ISSUE TITLE
phil-a-palooza!

### ISSUE THREAD

**Issue by bayounetta** [phil-a-mint/testcode#1]
set a day/afternoon for us to meet up and talk about our plans for our baby, phil

**Comment by bayounetta** [comment]
current idea being floated around is 21st or 22nd at the office. @fitzgen @amychurchwell

**Comment by fitzgen** [comment]
either one sounds good to me! soft preference for saturday lunch ish time if for no reason other than to pin something down that can be scheduled around

**Comment by bayounetta** [comment]
my plans for the 21st and 22nd have changed and I'll be out of town :/ sorry to throw a wrench into these plans

**Comment by amychurchwell** [comment]
unfortunately I also can't do the 21st/22nd because I'm in a wedding! 🎉
what about a day the following weekend? (28/29)

**Comment by fitzgen** [comment]
Bah -- I'll be out of town that weekend :(

Maybe we can do an evening during the week?

**Comment by amychurchwell** [comment]
+1 to weekday evening.

**Comment by bayounetta** [comment]
also +1 to a weekday evening!

**Comment by fitzgen** [comment]
how does the evening of monday the 23rd sound? I could also do tuesday the 24th

**Comment by amychurchwell** [comment]
monday the 23rd sounds great! (I can do any day that week except wednesday.)

**Comment by amychurchwell** [comment]
after work today still works for everyone?

🎵 _philllllllll~ a~ paloozaaaa!_

**Comment by fitzgen** [comment]
:metal:

**Comment by bayounetta** [comment]
https://twitter.com/nocontext_su/status/1175473501601456132?s=20
